// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Datas.proto

package com.youhaoxi.livelink.protocol.protobuf.demo;

public final class DataInfo {
  private DataInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DatasOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.youhaoxi.livelink.protocol.protobuf.demo.Datas)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .com.youhaoxi.livelink.protocol.protobuf.demo.Datas.DataType data_type = 1;</code>
     */
    boolean hasDataType();
    /**
     * <code>required .com.youhaoxi.livelink.protocol.protobuf.demo.Datas.DataType data_type = 1;</code>
     */
    Datas.DataType getDataType();

    /**
     * <code>optional .com.youhaoxi.livelink.protocol.protobuf.demo.Person person = 2;</code>
     */
    boolean hasPerson();
    /**
     * <code>optional .com.youhaoxi.livelink.protocol.protobuf.demo.Person person = 2;</code>
     */
    Person getPerson();
    /**
     * <code>optional .com.youhaoxi.livelink.protocol.protobuf.demo.Person person = 2;</code>
     */
    PersonOrBuilder getPersonOrBuilder();

    /**
     * <code>optional .com.youhaoxi.livelink.protocol.protobuf.demo.Dog dog = 3;</code>
     */
    boolean hasDog();
    /**
     * <code>optional .com.youhaoxi.livelink.protocol.protobuf.demo.Dog dog = 3;</code>
     */
    Dog getDog();
    /**
     * <code>optional .com.youhaoxi.livelink.protocol.protobuf.demo.Dog dog = 3;</code>
     */
    DogOrBuilder getDogOrBuilder();

    public Datas.TypeDataCase getTypeDataCase();
  }
  /**
   * Protobuf type {@code com.youhaoxi.livelink.protocol.protobuf.demo.Datas}
   */
  public  static final class Datas extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.youhaoxi.livelink.protocol.protobuf.demo.Datas)
      DatasOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Datas.newBuilder() to construct.
    private Datas(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Datas() {
      dataType_ = 1;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Datas(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              DataType value = DataType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                dataType_ = rawValue;
              }
              break;
            }
            case 18: {
              Person.Builder subBuilder = null;
              if (typeDataCase_ == 2) {
                subBuilder = ((Person) typeData_).toBuilder();
              }
              typeData_ =
                  input.readMessage(Person.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((Person) typeData_);
                typeData_ = subBuilder.buildPartial();
              }
              typeDataCase_ = 2;
              break;
            }
            case 26: {
              Dog.Builder subBuilder = null;
              if (typeDataCase_ == 3) {
                subBuilder = ((Dog) typeData_).toBuilder();
              }
              typeData_ =
                  input.readMessage(Dog.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((Dog) typeData_);
                typeData_ = subBuilder.buildPartial();
              }
              typeDataCase_ = 3;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DataInfo.internal_static_com_youhaoxi_livelink_protocol_protobuf_demo_Datas_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DataInfo.internal_static_com_youhaoxi_livelink_protocol_protobuf_demo_Datas_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Datas.class, Builder.class);
    }

    /**
     * Protobuf enum {@code com.youhaoxi.livelink.protocol.protobuf.demo.Datas.DataType}
     */
    public enum DataType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>personType = 1;</code>
       */
      personType(1),
      /**
       * <code>dogType = 2;</code>
       */
      dogType(2),
      ;

      /**
       * <code>personType = 1;</code>
       */
      public static final int personType_VALUE = 1;
      /**
       * <code>dogType = 2;</code>
       */
      public static final int dogType_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static DataType valueOf(int value) {
        return forNumber(value);
      }

      public static DataType forNumber(int value) {
        switch (value) {
          case 1: return personType;
          case 2: return dogType;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DataType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
              public DataType findValueByNumber(int number) {
                return DataType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Datas.getDescriptor().getEnumTypes().get(0);
      }

      private static final DataType[] VALUES = values();

      public static DataType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DataType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.youhaoxi.livelink.protocol.protobuf.demo.Datas.DataType)
    }

    private int bitField0_;
    private int typeDataCase_ = 0;
    private Object typeData_;
    public enum TypeDataCase
        implements com.google.protobuf.Internal.EnumLite {
      PERSON(2),
      DOG(3),
      TYPEDATA_NOT_SET(0);
      private final int value;
      private TypeDataCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static TypeDataCase valueOf(int value) {
        return forNumber(value);
      }

      public static TypeDataCase forNumber(int value) {
        switch (value) {
          case 2: return PERSON;
          case 3: return DOG;
          case 0: return TYPEDATA_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public TypeDataCase
    getTypeDataCase() {
      return TypeDataCase.forNumber(
          typeDataCase_);
    }

    public static final int DATA_TYPE_FIELD_NUMBER = 1;
    private int dataType_;
    /**
     * <code>required .com.youhaoxi.livelink.protocol.protobuf.demo.Datas.DataType data_type = 1;</code>
     */
    public boolean hasDataType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.youhaoxi.livelink.protocol.protobuf.demo.Datas.DataType data_type = 1;</code>
     */
    public DataType getDataType() {
      DataType result = DataType.valueOf(dataType_);
      return result == null ? DataType.personType : result;
    }

    public static final int PERSON_FIELD_NUMBER = 2;
    /**
     * <code>optional .com.youhaoxi.livelink.protocol.protobuf.demo.Person person = 2;</code>
     */
    public boolean hasPerson() {
      return typeDataCase_ == 2;
    }
    /**
     * <code>optional .com.youhaoxi.livelink.protocol.protobuf.demo.Person person = 2;</code>
     */
    public Person getPerson() {
      if (typeDataCase_ == 2) {
         return (Person) typeData_;
      }
      return Person.getDefaultInstance();
    }
    /**
     * <code>optional .com.youhaoxi.livelink.protocol.protobuf.demo.Person person = 2;</code>
     */
    public PersonOrBuilder getPersonOrBuilder() {
      if (typeDataCase_ == 2) {
         return (Person) typeData_;
      }
      return Person.getDefaultInstance();
    }

    public static final int DOG_FIELD_NUMBER = 3;
    /**
     * <code>optional .com.youhaoxi.livelink.protocol.protobuf.demo.Dog dog = 3;</code>
     */
    public boolean hasDog() {
      return typeDataCase_ == 3;
    }
    /**
     * <code>optional .com.youhaoxi.livelink.protocol.protobuf.demo.Dog dog = 3;</code>
     */
    public Dog getDog() {
      if (typeDataCase_ == 3) {
         return (Dog) typeData_;
      }
      return Dog.getDefaultInstance();
    }
    /**
     * <code>optional .com.youhaoxi.livelink.protocol.protobuf.demo.Dog dog = 3;</code>
     */
    public DogOrBuilder getDogOrBuilder() {
      if (typeDataCase_ == 3) {
         return (Dog) typeData_;
      }
      return Dog.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDataType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasPerson()) {
        if (!getPerson().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasDog()) {
        if (!getDog().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, dataType_);
      }
      if (typeDataCase_ == 2) {
        output.writeMessage(2, (Person) typeData_);
      }
      if (typeDataCase_ == 3) {
        output.writeMessage(3, (Dog) typeData_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, dataType_);
      }
      if (typeDataCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (Person) typeData_);
      }
      if (typeDataCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (Dog) typeData_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Datas)) {
        return super.equals(obj);
      }
      Datas other = (Datas) obj;

      boolean result = true;
      result = result && (hasDataType() == other.hasDataType());
      if (hasDataType()) {
        result = result && dataType_ == other.dataType_;
      }
      result = result && getTypeDataCase().equals(
          other.getTypeDataCase());
      if (!result) return false;
      switch (typeDataCase_) {
        case 2:
          result = result && getPerson()
              .equals(other.getPerson());
          break;
        case 3:
          result = result && getDog()
              .equals(other.getDog());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDataType()) {
        hash = (37 * hash) + DATA_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + dataType_;
      }
      switch (typeDataCase_) {
        case 2:
          hash = (37 * hash) + PERSON_FIELD_NUMBER;
          hash = (53 * hash) + getPerson().hashCode();
          break;
        case 3:
          hash = (37 * hash) + DOG_FIELD_NUMBER;
          hash = (53 * hash) + getDog().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Datas parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Datas parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Datas parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Datas parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Datas parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Datas parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Datas parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Datas parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Datas parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Datas parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Datas parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Datas parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Datas prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.youhaoxi.livelink.protocol.protobuf.demo.Datas}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.youhaoxi.livelink.protocol.protobuf.demo.Datas)
        DatasOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DataInfo.internal_static_com_youhaoxi_livelink_protocol_protobuf_demo_Datas_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DataInfo.internal_static_com_youhaoxi_livelink_protocol_protobuf_demo_Datas_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Datas.class, Builder.class);
      }

      // Construct using com.youhaoxi.livelink.protocol.protobuf.demo.DataInfo.Datas.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        dataType_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        typeDataCase_ = 0;
        typeData_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DataInfo.internal_static_com_youhaoxi_livelink_protocol_protobuf_demo_Datas_descriptor;
      }

      public Datas getDefaultInstanceForType() {
        return Datas.getDefaultInstance();
      }

      public Datas build() {
        Datas result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Datas buildPartial() {
        Datas result = new Datas(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.dataType_ = dataType_;
        if (typeDataCase_ == 2) {
          if (personBuilder_ == null) {
            result.typeData_ = typeData_;
          } else {
            result.typeData_ = personBuilder_.build();
          }
        }
        if (typeDataCase_ == 3) {
          if (dogBuilder_ == null) {
            result.typeData_ = typeData_;
          } else {
            result.typeData_ = dogBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.typeDataCase_ = typeDataCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Datas) {
          return mergeFrom((Datas)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Datas other) {
        if (other == Datas.getDefaultInstance()) return this;
        if (other.hasDataType()) {
          setDataType(other.getDataType());
        }
        switch (other.getTypeDataCase()) {
          case PERSON: {
            mergePerson(other.getPerson());
            break;
          }
          case DOG: {
            mergeDog(other.getDog());
            break;
          }
          case TYPEDATA_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDataType()) {
          return false;
        }
        if (hasPerson()) {
          if (!getPerson().isInitialized()) {
            return false;
          }
        }
        if (hasDog()) {
          if (!getDog().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Datas parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Datas) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int typeDataCase_ = 0;
      private Object typeData_;
      public TypeDataCase
          getTypeDataCase() {
        return TypeDataCase.forNumber(
            typeDataCase_);
      }

      public Builder clearTypeData() {
        typeDataCase_ = 0;
        typeData_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private int dataType_ = 1;
      /**
       * <code>required .com.youhaoxi.livelink.protocol.protobuf.demo.Datas.DataType data_type = 1;</code>
       */
      public boolean hasDataType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.youhaoxi.livelink.protocol.protobuf.demo.Datas.DataType data_type = 1;</code>
       */
      public DataType getDataType() {
        DataType result = DataType.valueOf(dataType_);
        return result == null ? DataType.personType : result;
      }
      /**
       * <code>required .com.youhaoxi.livelink.protocol.protobuf.demo.Datas.DataType data_type = 1;</code>
       */
      public Builder setDataType(DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        dataType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .com.youhaoxi.livelink.protocol.protobuf.demo.Datas.DataType data_type = 1;</code>
       */
      public Builder clearDataType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        dataType_ = 1;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          Person, Person.Builder, PersonOrBuilder> personBuilder_;
      /**
       * <code>optional .com.youhaoxi.livelink.protocol.protobuf.demo.Person person = 2;</code>
       */
      public boolean hasPerson() {
        return typeDataCase_ == 2;
      }
      /**
       * <code>optional .com.youhaoxi.livelink.protocol.protobuf.demo.Person person = 2;</code>
       */
      public Person getPerson() {
        if (personBuilder_ == null) {
          if (typeDataCase_ == 2) {
            return (Person) typeData_;
          }
          return Person.getDefaultInstance();
        } else {
          if (typeDataCase_ == 2) {
            return personBuilder_.getMessage();
          }
          return Person.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.youhaoxi.livelink.protocol.protobuf.demo.Person person = 2;</code>
       */
      public Builder setPerson(Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          typeData_ = value;
          onChanged();
        } else {
          personBuilder_.setMessage(value);
        }
        typeDataCase_ = 2;
        return this;
      }
      /**
       * <code>optional .com.youhaoxi.livelink.protocol.protobuf.demo.Person person = 2;</code>
       */
      public Builder setPerson(
          Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          typeData_ = builderForValue.build();
          onChanged();
        } else {
          personBuilder_.setMessage(builderForValue.build());
        }
        typeDataCase_ = 2;
        return this;
      }
      /**
       * <code>optional .com.youhaoxi.livelink.protocol.protobuf.demo.Person person = 2;</code>
       */
      public Builder mergePerson(Person value) {
        if (personBuilder_ == null) {
          if (typeDataCase_ == 2 &&
              typeData_ != Person.getDefaultInstance()) {
            typeData_ = Person.newBuilder((Person) typeData_)
                .mergeFrom(value).buildPartial();
          } else {
            typeData_ = value;
          }
          onChanged();
        } else {
          if (typeDataCase_ == 2) {
            personBuilder_.mergeFrom(value);
          }
          personBuilder_.setMessage(value);
        }
        typeDataCase_ = 2;
        return this;
      }
      /**
       * <code>optional .com.youhaoxi.livelink.protocol.protobuf.demo.Person person = 2;</code>
       */
      public Builder clearPerson() {
        if (personBuilder_ == null) {
          if (typeDataCase_ == 2) {
            typeDataCase_ = 0;
            typeData_ = null;
            onChanged();
          }
        } else {
          if (typeDataCase_ == 2) {
            typeDataCase_ = 0;
            typeData_ = null;
          }
          personBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .com.youhaoxi.livelink.protocol.protobuf.demo.Person person = 2;</code>
       */
      public Person.Builder getPersonBuilder() {
        return getPersonFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.youhaoxi.livelink.protocol.protobuf.demo.Person person = 2;</code>
       */
      public PersonOrBuilder getPersonOrBuilder() {
        if ((typeDataCase_ == 2) && (personBuilder_ != null)) {
          return personBuilder_.getMessageOrBuilder();
        } else {
          if (typeDataCase_ == 2) {
            return (Person) typeData_;
          }
          return Person.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.youhaoxi.livelink.protocol.protobuf.demo.Person person = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Person, Person.Builder, PersonOrBuilder>
          getPersonFieldBuilder() {
        if (personBuilder_ == null) {
          if (!(typeDataCase_ == 2)) {
            typeData_ = Person.getDefaultInstance();
          }
          personBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Person, Person.Builder, PersonOrBuilder>(
                  (Person) typeData_,
                  getParentForChildren(),
                  isClean());
          typeData_ = null;
        }
        typeDataCase_ = 2;
        onChanged();;
        return personBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          Dog, Dog.Builder, DogOrBuilder> dogBuilder_;
      /**
       * <code>optional .com.youhaoxi.livelink.protocol.protobuf.demo.Dog dog = 3;</code>
       */
      public boolean hasDog() {
        return typeDataCase_ == 3;
      }
      /**
       * <code>optional .com.youhaoxi.livelink.protocol.protobuf.demo.Dog dog = 3;</code>
       */
      public Dog getDog() {
        if (dogBuilder_ == null) {
          if (typeDataCase_ == 3) {
            return (Dog) typeData_;
          }
          return Dog.getDefaultInstance();
        } else {
          if (typeDataCase_ == 3) {
            return dogBuilder_.getMessage();
          }
          return Dog.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.youhaoxi.livelink.protocol.protobuf.demo.Dog dog = 3;</code>
       */
      public Builder setDog(Dog value) {
        if (dogBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          typeData_ = value;
          onChanged();
        } else {
          dogBuilder_.setMessage(value);
        }
        typeDataCase_ = 3;
        return this;
      }
      /**
       * <code>optional .com.youhaoxi.livelink.protocol.protobuf.demo.Dog dog = 3;</code>
       */
      public Builder setDog(
          Dog.Builder builderForValue) {
        if (dogBuilder_ == null) {
          typeData_ = builderForValue.build();
          onChanged();
        } else {
          dogBuilder_.setMessage(builderForValue.build());
        }
        typeDataCase_ = 3;
        return this;
      }
      /**
       * <code>optional .com.youhaoxi.livelink.protocol.protobuf.demo.Dog dog = 3;</code>
       */
      public Builder mergeDog(Dog value) {
        if (dogBuilder_ == null) {
          if (typeDataCase_ == 3 &&
              typeData_ != Dog.getDefaultInstance()) {
            typeData_ = Dog.newBuilder((Dog) typeData_)
                .mergeFrom(value).buildPartial();
          } else {
            typeData_ = value;
          }
          onChanged();
        } else {
          if (typeDataCase_ == 3) {
            dogBuilder_.mergeFrom(value);
          }
          dogBuilder_.setMessage(value);
        }
        typeDataCase_ = 3;
        return this;
      }
      /**
       * <code>optional .com.youhaoxi.livelink.protocol.protobuf.demo.Dog dog = 3;</code>
       */
      public Builder clearDog() {
        if (dogBuilder_ == null) {
          if (typeDataCase_ == 3) {
            typeDataCase_ = 0;
            typeData_ = null;
            onChanged();
          }
        } else {
          if (typeDataCase_ == 3) {
            typeDataCase_ = 0;
            typeData_ = null;
          }
          dogBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .com.youhaoxi.livelink.protocol.protobuf.demo.Dog dog = 3;</code>
       */
      public Dog.Builder getDogBuilder() {
        return getDogFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.youhaoxi.livelink.protocol.protobuf.demo.Dog dog = 3;</code>
       */
      public DogOrBuilder getDogOrBuilder() {
        if ((typeDataCase_ == 3) && (dogBuilder_ != null)) {
          return dogBuilder_.getMessageOrBuilder();
        } else {
          if (typeDataCase_ == 3) {
            return (Dog) typeData_;
          }
          return Dog.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.youhaoxi.livelink.protocol.protobuf.demo.Dog dog = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Dog, Dog.Builder, DogOrBuilder>
          getDogFieldBuilder() {
        if (dogBuilder_ == null) {
          if (!(typeDataCase_ == 3)) {
            typeData_ = Dog.getDefaultInstance();
          }
          dogBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Dog, Dog.Builder, DogOrBuilder>(
                  (Dog) typeData_,
                  getParentForChildren(),
                  isClean());
          typeData_ = null;
        }
        typeDataCase_ = 3;
        onChanged();;
        return dogBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.youhaoxi.livelink.protocol.protobuf.demo.Datas)
    }

    // @@protoc_insertion_point(class_scope:com.youhaoxi.livelink.protocol.protobuf.demo.Datas)
    private static final Datas DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Datas();
    }

    public static Datas getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<Datas>
        PARSER = new com.google.protobuf.AbstractParser<Datas>() {
      public Datas parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Datas(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Datas> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Datas> getParserForType() {
      return PARSER;
    }

    public Datas getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.youhaoxi.livelink.protocol.protobuf.demo.Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 2;</code>
     */
    String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional .com.youhaoxi.livelink.protocol.protobuf.demo.Person.Gender gender = 3;</code>
     */
    boolean hasGender();
    /**
     * <code>optional .com.youhaoxi.livelink.protocol.protobuf.demo.Person.Gender gender = 3;</code>
     */
    Person.Gender getGender();
  }
  /**
   * Protobuf type {@code com.youhaoxi.livelink.protocol.protobuf.demo.Person}
   */
  public  static final class Person extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.youhaoxi.livelink.protocol.protobuf.demo.Person)
      PersonOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Person() {
      id_ = 0;
      name_ = "";
      gender_ = 1;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              Gender value = Gender.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                gender_ = rawValue;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DataInfo.internal_static_com_youhaoxi_livelink_protocol_protobuf_demo_Person_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DataInfo.internal_static_com_youhaoxi_livelink_protocol_protobuf_demo_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Person.class, Builder.class);
    }

    /**
     * Protobuf enum {@code com.youhaoxi.livelink.protocol.protobuf.demo.Person.Gender}
     */
    public enum Gender
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>male = 1;</code>
       */
      male(1),
      /**
       * <code>female = 2;</code>
       */
      female(2),
      ;

      /**
       * <code>male = 1;</code>
       */
      public static final int male_VALUE = 1;
      /**
       * <code>female = 2;</code>
       */
      public static final int female_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static Gender valueOf(int value) {
        return forNumber(value);
      }

      public static Gender forNumber(int value) {
        switch (value) {
          case 1: return male;
          case 2: return female;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Gender>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Gender> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Gender>() {
              public Gender findValueByNumber(int number) {
                return Gender.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Person.getDescriptor().getEnumTypes().get(0);
      }

      private static final Gender[] VALUES = values();

      public static Gender valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Gender(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.youhaoxi.livelink.protocol.protobuf.demo.Person.Gender)
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GENDER_FIELD_NUMBER = 3;
    private int gender_;
    /**
     * <code>optional .com.youhaoxi.livelink.protocol.protobuf.demo.Person.Gender gender = 3;</code>
     */
    public boolean hasGender() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .com.youhaoxi.livelink.protocol.protobuf.demo.Person.Gender gender = 3;</code>
     */
    public Gender getGender() {
      Gender result = Gender.valueOf(gender_);
      return result == null ? Gender.male : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, gender_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, gender_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Person)) {
        return super.equals(obj);
      }
      Person other = (Person) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasGender() == other.hasGender());
      if (hasGender()) {
        result = result && gender_ == other.gender_;
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasGender()) {
        hash = (37 * hash) + GENDER_FIELD_NUMBER;
        hash = (53 * hash) + gender_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Person parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Person parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.youhaoxi.livelink.protocol.protobuf.demo.Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.youhaoxi.livelink.protocol.protobuf.demo.Person)
        PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DataInfo.internal_static_com_youhaoxi_livelink_protocol_protobuf_demo_Person_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DataInfo.internal_static_com_youhaoxi_livelink_protocol_protobuf_demo_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Person.class, Builder.class);
      }

      // Construct using com.youhaoxi.livelink.protocol.protobuf.demo.DataInfo.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        gender_ = 1;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DataInfo.internal_static_com_youhaoxi_livelink_protocol_protobuf_demo_Person_descriptor;
      }

      public Person getDefaultInstanceForType() {
        return Person.getDefaultInstance();
      }

      public Person build() {
        Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Person buildPartial() {
        Person result = new Person(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.gender_ = gender_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Person) {
          return mergeFrom((Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Person other) {
        if (other == Person.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasGender()) {
          setGender(other.getGender());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Person) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private int gender_ = 1;
      /**
       * <code>optional .com.youhaoxi.livelink.protocol.protobuf.demo.Person.Gender gender = 3;</code>
       */
      public boolean hasGender() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .com.youhaoxi.livelink.protocol.protobuf.demo.Person.Gender gender = 3;</code>
       */
      public Gender getGender() {
        Gender result = Gender.valueOf(gender_);
        return result == null ? Gender.male : result;
      }
      /**
       * <code>optional .com.youhaoxi.livelink.protocol.protobuf.demo.Person.Gender gender = 3;</code>
       */
      public Builder setGender(Gender value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        gender_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.youhaoxi.livelink.protocol.protobuf.demo.Person.Gender gender = 3;</code>
       */
      public Builder clearGender() {
        bitField0_ = (bitField0_ & ~0x00000004);
        gender_ = 1;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.youhaoxi.livelink.protocol.protobuf.demo.Person)
    }

    // @@protoc_insertion_point(class_scope:com.youhaoxi.livelink.protocol.protobuf.demo.Person)
    private static final Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Person();
    }

    public static Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<Person>
        PARSER = new com.google.protobuf.AbstractParser<Person>() {
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Person> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    public Person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DogOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.youhaoxi.livelink.protocol.protobuf.demo.Dog)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required float height = 1;</code>
     */
    boolean hasHeight();
    /**
     * <code>required float height = 1;</code>
     */
    float getHeight();

    /**
     * <code>optional string color = 2;</code>
     */
    boolean hasColor();
    /**
     * <code>optional string color = 2;</code>
     */
    String getColor();
    /**
     * <code>optional string color = 2;</code>
     */
    com.google.protobuf.ByteString
        getColorBytes();

    /**
     * <code>optional int64 age = 3;</code>
     */
    boolean hasAge();
    /**
     * <code>optional int64 age = 3;</code>
     */
    long getAge();
  }
  /**
   * Protobuf type {@code com.youhaoxi.livelink.protocol.protobuf.demo.Dog}
   */
  public  static final class Dog extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.youhaoxi.livelink.protocol.protobuf.demo.Dog)
      DogOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Dog.newBuilder() to construct.
    private Dog(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Dog() {
      height_ = 0F;
      color_ = "";
      age_ = 0L;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Dog(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              height_ = input.readFloat();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              color_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              age_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DataInfo.internal_static_com_youhaoxi_livelink_protocol_protobuf_demo_Dog_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DataInfo.internal_static_com_youhaoxi_livelink_protocol_protobuf_demo_Dog_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Dog.class, Builder.class);
    }

    private int bitField0_;
    public static final int HEIGHT_FIELD_NUMBER = 1;
    private float height_;
    /**
     * <code>required float height = 1;</code>
     */
    public boolean hasHeight() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required float height = 1;</code>
     */
    public float getHeight() {
      return height_;
    }

    public static final int COLOR_FIELD_NUMBER = 2;
    private volatile Object color_;
    /**
     * <code>optional string color = 2;</code>
     */
    public boolean hasColor() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string color = 2;</code>
     */
    public String getColor() {
      Object ref = color_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          color_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string color = 2;</code>
     */
    public com.google.protobuf.ByteString
        getColorBytes() {
      Object ref = color_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        color_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 3;
    private long age_;
    /**
     * <code>optional int64 age = 3;</code>
     */
    public boolean hasAge() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 age = 3;</code>
     */
    public long getAge() {
      return age_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasHeight()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFloat(1, height_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, color_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, age_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, height_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, color_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, age_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Dog)) {
        return super.equals(obj);
      }
      Dog other = (Dog) obj;

      boolean result = true;
      result = result && (hasHeight() == other.hasHeight());
      if (hasHeight()) {
        result = result && (
            Float.floatToIntBits(getHeight())
            == Float.floatToIntBits(
                other.getHeight()));
      }
      result = result && (hasColor() == other.hasColor());
      if (hasColor()) {
        result = result && getColor()
            .equals(other.getColor());
      }
      result = result && (hasAge() == other.hasAge());
      if (hasAge()) {
        result = result && (getAge()
            == other.getAge());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeight()) {
        hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
        hash = (53 * hash) + Float.floatToIntBits(
            getHeight());
      }
      if (hasColor()) {
        hash = (37 * hash) + COLOR_FIELD_NUMBER;
        hash = (53 * hash) + getColor().hashCode();
      }
      if (hasAge()) {
        hash = (37 * hash) + AGE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getAge());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Dog parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Dog parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Dog parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Dog parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Dog parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Dog parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Dog parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Dog parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Dog parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Dog parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Dog parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Dog parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Dog prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.youhaoxi.livelink.protocol.protobuf.demo.Dog}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.youhaoxi.livelink.protocol.protobuf.demo.Dog)
        DogOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DataInfo.internal_static_com_youhaoxi_livelink_protocol_protobuf_demo_Dog_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DataInfo.internal_static_com_youhaoxi_livelink_protocol_protobuf_demo_Dog_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Dog.class, Builder.class);
      }

      // Construct using com.youhaoxi.livelink.protocol.protobuf.demo.DataInfo.Dog.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        height_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000001);
        color_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        age_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DataInfo.internal_static_com_youhaoxi_livelink_protocol_protobuf_demo_Dog_descriptor;
      }

      public Dog getDefaultInstanceForType() {
        return Dog.getDefaultInstance();
      }

      public Dog build() {
        Dog result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Dog buildPartial() {
        Dog result = new Dog(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.height_ = height_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.color_ = color_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.age_ = age_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Dog) {
          return mergeFrom((Dog)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Dog other) {
        if (other == Dog.getDefaultInstance()) return this;
        if (other.hasHeight()) {
          setHeight(other.getHeight());
        }
        if (other.hasColor()) {
          bitField0_ |= 0x00000002;
          color_ = other.color_;
          onChanged();
        }
        if (other.hasAge()) {
          setAge(other.getAge());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasHeight()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Dog parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Dog) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private float height_ ;
      /**
       * <code>required float height = 1;</code>
       */
      public boolean hasHeight() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required float height = 1;</code>
       */
      public float getHeight() {
        return height_;
      }
      /**
       * <code>required float height = 1;</code>
       */
      public Builder setHeight(float value) {
        bitField0_ |= 0x00000001;
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float height = 1;</code>
       */
      public Builder clearHeight() {
        bitField0_ = (bitField0_ & ~0x00000001);
        height_ = 0F;
        onChanged();
        return this;
      }

      private Object color_ = "";
      /**
       * <code>optional string color = 2;</code>
       */
      public boolean hasColor() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string color = 2;</code>
       */
      public String getColor() {
        Object ref = color_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            color_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string color = 2;</code>
       */
      public com.google.protobuf.ByteString
          getColorBytes() {
        Object ref = color_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          color_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string color = 2;</code>
       */
      public Builder setColor(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        color_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string color = 2;</code>
       */
      public Builder clearColor() {
        bitField0_ = (bitField0_ & ~0x00000002);
        color_ = getDefaultInstance().getColor();
        onChanged();
        return this;
      }
      /**
       * <code>optional string color = 2;</code>
       */
      public Builder setColorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        color_ = value;
        onChanged();
        return this;
      }

      private long age_ ;
      /**
       * <code>optional int64 age = 3;</code>
       */
      public boolean hasAge() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 age = 3;</code>
       */
      public long getAge() {
        return age_;
      }
      /**
       * <code>optional int64 age = 3;</code>
       */
      public Builder setAge(long value) {
        bitField0_ |= 0x00000004;
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 age = 3;</code>
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000004);
        age_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.youhaoxi.livelink.protocol.protobuf.demo.Dog)
    }

    // @@protoc_insertion_point(class_scope:com.youhaoxi.livelink.protocol.protobuf.demo.Dog)
    private static final Dog DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Dog();
    }

    public static Dog getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<Dog>
        PARSER = new com.google.protobuf.AbstractParser<Dog>() {
      public Dog parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Dog(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Dog> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Dog> getParserForType() {
      return PARSER;
    }

    public Dog getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_youhaoxi_livelink_protocol_protobuf_demo_Datas_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_youhaoxi_livelink_protocol_protobuf_demo_Datas_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_youhaoxi_livelink_protocol_protobuf_demo_Person_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_youhaoxi_livelink_protocol_protobuf_demo_Person_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_youhaoxi_livelink_protocol_protobuf_demo_Dog_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_youhaoxi_livelink_protocol_protobuf_demo_Dog_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013Datas.proto\022,com.youhaoxi.livelink.pro" +
      "tocol.protobuf.demo\"\230\002\n\005Datas\022O\n\tdata_ty" +
      "pe\030\001 \002(\0162<.com.youhaoxi.livelink.protoco" +
      "l.protobuf.demo.Datas.DataType\022F\n\006person" +
      "\030\002 \001(\01324.com.youhaoxi.livelink.protocol." +
      "protobuf.demo.PersonH\000\022@\n\003dog\030\003 \001(\01321.co" +
      "m.youhaoxi.livelink.protocol.protobuf.de" +
      "mo.DogH\000\"\'\n\010DataType\022\016\n\npersonType\020\001\022\013\n\007" +
      "dogType\020\002B\013\n\ttype_data\"\217\001\n\006Person\022\n\n\002id\030" +
      "\001 \002(\005\022\014\n\004name\030\002 \001(\t\022K\n\006gender\030\003 \001(\0162;.co" +
      "m.youhaoxi.livelink.protocol.protobuf.de" +
      "mo.Person.Gender\"\036\n\006Gender\022\010\n\004male\020\001\022\n\n\006" +
      "female\020\002\"1\n\003Dog\022\016\n\006height\030\001 \002(\002\022\r\n\005color" +
      "\030\002 \001(\t\022\013\n\003age\030\003 \001(\003B8\n,com.youhaoxi.live" +
      "link.protocol.protobuf.demoB\010DataInfo"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_youhaoxi_livelink_protocol_protobuf_demo_Datas_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_youhaoxi_livelink_protocol_protobuf_demo_Datas_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_youhaoxi_livelink_protocol_protobuf_demo_Datas_descriptor,
        new String[] { "DataType", "Person", "Dog", "TypeData", });
    internal_static_com_youhaoxi_livelink_protocol_protobuf_demo_Person_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_youhaoxi_livelink_protocol_protobuf_demo_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_youhaoxi_livelink_protocol_protobuf_demo_Person_descriptor,
        new String[] { "Id", "Name", "Gender", });
    internal_static_com_youhaoxi_livelink_protocol_protobuf_demo_Dog_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_youhaoxi_livelink_protocol_protobuf_demo_Dog_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_youhaoxi_livelink_protocol_protobuf_demo_Dog_descriptor,
        new String[] { "Height", "Color", "Age", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
